### ISSUE TITLE
Multiple retries happen if an endpoint is too slow to respond in time

### ISSUE THREAD

**Issue by lloydmeta** [m3dev/octoparts#129]
Zipkin shows that when an endpoint is slow and fails to respond in time, we actually fire another request.

Likely caused the by the messy recovers going on in [PartResponseCachingSupport](https://github.com/m3dev/octoparts/blob/develop/app/com/m3/octoparts/cache/PartResponseCachingSupport.scala)

Probably solvable by caching the error type [here](https://github.com/m3dev/octoparts/blob/develop/app/com/m3/octoparts/cache/PartResponseCachingSupport.scala#L79-L81)

**Comment by mauhiz** [comment]
Fixed by #130
