### ISSUE TITLE
High conn_yields in Memcached stats

### ISSUE THREAD

**Issue by lloydmeta** [m3dev/octoparts#137]
Been noticing a high amount of conn_yields in our Memcached stats

```
...
STAT conn_yields 37195
...
```

Need to investigate further, but first hunch is that we are concurrently sending a lot of gets through Shade/Spymemcached, which batches them into multi-gets; since we are running Memcached at defaults, the server might be cutting us off to prevent resource starvation of other clients.

Possible courses of action include:

1. Increasing/setting -R 
2. Trying to configure the client to send smaller batches of multi-gets.

References:

[Tuning Memcached](https://blog.engineyard.com/2015/fine-tuning-memcached)

>Connection yields are the amount of times the memcached server has throttled a specific client. If you have conn_yields you are likely using large multi-get requests. It is possible to lower the sizes of your multi-get operations or increase the -R value, or both.

>The default value of -R is 50 connections from a client before throttling. Note that not all memcached clients respond the same way to the connection yield throttling. Some clients reconnect without an issue, while others may report that the memcached server is unavailable. You will likely want to increase these numbers until you no longer see the conn_yield statistic being throttled.

[Spymemcached Optimisations](https://code.google.com/p/spymemcached/wiki/Optimizations)

>In the process of finding data to write over the wire, the IO thread will notice when there are multiple get requests in a row and collapse them into a single multi-get request with deduplicated keys.

>For example, several outstanding requests in a queue for a single server that look like this: [a], [b], [a, b, c], [a], [d], will be collapsed into a single request for [a, b, c, d] and then the results will be delivered to the respective callers (five in this case).

**Comment by mauhiz** [comment]
From the spymemcached client sources, [the multi-get max size is hardcoded to 4096](https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java#L44)

**Comment by mauhiz** [comment]
> Note that not all memcached clients respond the same way to the connection yield throttling. Some clients reconnect without an issue, while others may report that the memcached server is unavailable.

I think that is because on yield, [memcached does something that looks very arbitrary]( https://github.com/memcached/memcached/blob/c5530027c8ea28674358327ab8212ebaf014c848/memcached.c#L4132-L4143) and may trigger a disconnection of some clients

**Comment by mauhiz** [comment]
Based on this, I would recommend to avoid yields when possible by setting -R to 4096, but that would require extensive testing under load :)

**Comment by lloydmeta** [comment]
I agree:

    conn_set_state(c, conn_closing);

Does *not* look good at all.

Given that we can't control the max in spymemcached (thanks for finding that), we don't really have a choice. 

I will leave this ticket open as a reminder to myself to least leave a note *somewhere*

**Comment by lloydmeta** [comment]
Did some basic testing, setting -R did indeed fix the conn_yields w/ no discernible problems during testing. Tracking conn_yields over 10 mins of Jmeter w/ 25 concurrent users: 

![screen shot 2015-03-16 at 15 34 47](https://cloud.githubusercontent.com/assets/914805/6661601/1746c844-cbf2-11e4-956d-711e85515033.png)

Closing this ticket now; will update docs.
