### ISSUE TITLE
Monitoring: do not trigger an alert for open circuits

### ISSUE THREAD

**Issue by mauhiz** [m3dev/octoparts#144]
Rationale :
- parts are already monitored with email alerts
- it can be expected that most of the time, Octoparts is faring well

Suggestions :
- report open circuits but return "GREEN" anyways
- do not report open circuits

**Comment by seratch** [comment]
Thanks as usual. Both of your suggestions are good to me.

>do not report open circuits

If we go with this, I think it's acceptable to separate the monitoring endpoint into Octoparts app itself health and another one which shows a list of its open circuits, although we won't use the second one.

**Comment by lloydmeta** [comment]
Closed by #150
