### ISSUE TITLE
Allow selecting which parts to export

### ISSUE THREAD

**Issue by lloydmeta** [m3dev/octoparts#163]
Right now you can't export a subset of registered params.

@xevix for the idea.

**Comment by xevix** [comment]
On a related note, a few other ideas come to mind which I might make separate issues of if they make sense. 

* Syncing a set of parts from one Octoparts instance to another
  * A small setting interface to link 2 instances together so they know about each other
  * A way to select multiple endpoints to sync from Octoparts A to Octoparts B

* #164 allows for mass exporting. It might also make sense to have mass importing (right now it's 1 file at a time)

**Comment by lloydmeta** [comment]
Closing due to #164
