### ISSUE TITLE
defect : Cache-Group (member of  parameter) is not exported in the admin screen.

### ISSUE THREAD

**Issue by tok12** [m3dev/octoparts#95]
Please see below:
1. Cache-Group (member of  parameter) is not exported.
 ->  "cacheGroups":[]
2. Cache-Group (member of  Api endpoint) is exported.
 -> "cacheGroups":[{"name":"xxx","owner":"yyy","description":"zzz"}]

In addition, import was successful.

**Comment by mauhiz** [comment]
The HttpPartConfigRepository is not eager loading part parameter cache groups; indeed this is not necessary for other uses of the HttpPartConfig.
